<#
.SYNOPSIS
Builds a startup context document from the four Weave identity files.

.EXAMPLE
.\Load-WeaveSessionContext.ps1 -PrintOnly

.EXAMPLE
.\Load-WeaveSessionContext.ps1 -OutputPath .\weave-session-context.md
#>

param(
    [string]$WorktreePath = "",
    [string]$OutputPath = "",
    [switch]$PrintOnly,
    [switch]$AllowMissing
)

$ErrorActionPreference = "Stop"

$script:Utf8WithBom = New-Object System.Text.UTF8Encoding -ArgumentList $true
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

$files = @(
    "C:\Users\anyth\DEV\homunculus\Weave\Identities\WeaveInstruction.md",
    "C:\Users\anyth\DEV\homunculus\Weave\Identities\GrandDigest.txt",
    "C:\Users\anyth\DEV\homunculus\Weave\Identities\ShadowGrandDigest.txt",
    "C:\Users\anyth\DEV\homunculus\Weave\Identities\IntentionPad.md"
)

if ([string]::IsNullOrWhiteSpace($WorktreePath)) {
    if (-not [string]::IsNullOrWhiteSpace($env:CODEX_WORKTREE_PATH)) {
        $WorktreePath = $env:CODEX_WORKTREE_PATH
    }
    else {
        $WorktreePath = (Get-Location).Path
    }
}

$WorktreePath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($WorktreePath)

if ([string]::IsNullOrWhiteSpace($OutputPath) -and -not $PrintOnly) {
    $OutputPath = Join-Path -Path $WorktreePath -ChildPath ".codex\weave-session-context.md"
}

function Add-Line {
    param(
        [System.Text.StringBuilder]$Builder,
        [string]$Text = ""
    )

    [void]$Builder.AppendLine($Text)
}

$missing = @($files | Where-Object { -not (Test-Path -LiteralPath $_ -PathType Leaf) })
if ($missing.Count -gt 0 -and -not $AllowMissing) {
    Write-Error ("Missing Weave identity file(s):`n" + ($missing -join "`n"))
}

$builder = [System.Text.StringBuilder]::new()
Add-Line -Builder $builder -Text "# Weave Session Startup Context"
Add-Line -Builder $builder
Add-Line -Builder $builder -Text "This file is generated by `Load-WeaveSessionContext.ps1` during Codex worktree setup."
Add-Line -Builder $builder -Text "At session start, read this file after `AGENTS.md` and treat it as durable session context."
Add-Line -Builder $builder
Add-Line -Builder $builder -Text "<weave-session-context generated-at=""$((Get-Date).ToString("o"))"">"

foreach ($file in $files) {
    Add-Line $builder
    Add-Line $builder "<weave-identity-file path=""$file"">"

    if (Test-Path -LiteralPath $file -PathType Leaf) {
        $content = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
        Add-Line -Builder $builder -Text ($content.TrimEnd())
    }
    else {
        Add-Line -Builder $builder -Text "[missing]"
    }

    Add-Line -Builder $builder -Text "</weave-identity-file>"
}

Add-Line -Builder $builder
Add-Line -Builder $builder -Text "</weave-session-context>"

$result = $builder.ToString()

if ($PrintOnly -or [string]::IsNullOrWhiteSpace($OutputPath)) {
    Write-Output $result
}
else {
    $resolvedOutputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)
    $outputDirectory = Split-Path -Parent $resolvedOutputPath

    if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
        New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
    }

    [System.IO.File]::WriteAllText($resolvedOutputPath, $result, $script:Utf8WithBom)
    Write-Output "Wrote Weave session context to: $resolvedOutputPath"
}
